### ISSUE TITLE
Needs a 64 bit Trusty image

### ISSUE THREAD

**Issue by johnennewdeeson** [dan-sprog/vdd#12]
Current VDD uses a 32 bit Ubuntu precise as a base - 12.04 which Acquia just migrated away from

We need a 64 bit Ubuntu Trusty base instead - 14.04

**Comment by ghost** [comment]
Created a new trust64 branch for this

**Comment by ghost** [comment]
Needs an updated apache2 cookbook - added in 2.0.0 (up from 1.10)

**Comment by ghost** [comment]
Needs an updated PHP cookbook - added in 1.5.0 (up from 1.4.1)

**Comment by ghost** [comment]
This is now present on trust64 branch
