### ISSUE TITLE
phpmyadmin stopped working

### ISSUE THREAD

**Issue by johnennewdeeson** [dan-sprog/vdd#14]
phpmyadmin stopped working after mariadb update

**Comment by ghost** [comment]
AH00526: Syntax error on line 30 of /etc/apache2/conf-enabled/phpmyadmin.conf

**Comment by ghost** [comment]
Problem appears to be apache2 modules auth_baisc and authz_user being deliberately disabled in apache2.rb

**Comment by ghost** [comment]
Fixed by last commit
