### ISSUE TITLE
running drush master-execute causes all aliases environments to be contacted by drush

### ISSUE THREAD

**Issue by johnennewdeeson** [dan-sprog/vdd#15]
running drush master-execute causes all aliases environments to be contacted by drush

As the vagrant box has no ssh keys for the other environments e.g. production it can't do anything to it but it generates errors.

drush uses @self when executing child processes - it must be this causing issues.

**Comment by ghost** [comment]
This happens because the aliases file stored in sites/all/drush has the same name as the site. Always call this file sites.aliases.drushrc.php and this problem goes away.

**Comment by ghost** [comment]
Added this to the documentation
