### ISSUE TITLE
Drush sql-cli

### ISSUE THREAD

**Issue by angry-dan** [dan-sprog/vdd#18]
sql-cli doesn't work for reasons that I don't fully understand, but I wish it did! Currently you have to ssh in then you can `drush @site sql-cli`

**Comment by ghost** [comment]
Probably the same reason you can't do it on acquia - by adding the alias, the command is actually executed on the VDD box via ssh. You really want to be able to run it without the alias.

**Comment by ghost** [comment]
You'll probably notice that redirecting into sql-cli does work though

```
drush @vdd sql-cli < ../backups/something.sql
```

**Comment by ghost** [comment]
Dan!

We have to patch drush to make this work.  Regard e vous:

```
ssh dev.local -o "RequestTTY Yes" 'mysql -u root -proot'
```

**Comment by ghost** [comment]
and before that - just put this in your ssh config ...

```
RequestTTY Yes
```

**Comment by angry-dan** [comment]
Turns out this also works: "ssh dev.local -t 'mysql -u root -proot'"

Why isn't this default though?!

**Comment by ghost** [comment]
Added to the VDD documentation
