### ISSUE TITLE
Command line utility

### ISSUE THREAD

**Issue by angry-dan** [dan-sprog/vdd#19]
What would make VDD really awesome is some kind of vdd cli...
(Symfony based of course)

So:

``` bash
$cd ~/Sites/some-project
$vdd install
Project shortname? [some-project]
Path to docroot? [docroot]
Import a DB? #Paste a DB backup path here. .gz files are decompressed automatically.
Re-provision machine now? [yes]
Done! Visit your new site: http://some-project.dev
```

And off it goes... backup and update config.json then re-run vagrant --provision.

How cool would that be?! Steps to set up a site go down to just:

git clone
vdd install, enter, enter, cmd+v, enter
click link

**Comment by ghost** [comment]
moved to teamdeeson
