### ISSUE TITLE
Preinstall grunt and compass

### ISSUE THREAD

**Issue by johnennewdeeson** [dan-sprog/vdd#3]
Have CSS & JS compile automatcially - needs either settings per site or a careful best practice standard for folder locations.

**Comment by ghost** [comment]
I am working on this now using instructions here:

https://www.deeson.co.uk/labs/using-grunt-bootstrap-compass-and-sass-drupal-sub-theme

and chef cook book here:

https://github.com/redguide/nodejs

**Comment by ghost** [comment]
This is tested and working. Pushed code changes into master. The documentation has been updated with a section dedicated to setting up your example site with grunt.
