### ISSUE TITLE
Creating a settings file per site

### ISSUE THREAD

**Issue by johnennewdeeson** [dan-sprog/vdd#4]
Create a centralised settings file per site like Acquia do. This would be like the aliases file but could inlcude things such as:
- Base URL
- Apachesolr configuration defaults

**Comment by angry-dan** [comment]
We already have this in the drushrc file that's output. Can we flex that with the kinds of things you're hoping for?
I guess a single require_once on a configuration file would be ideal. /etc/drupal/settings/[sitename].php ?
I think I've probably got enough Chef knowledge to make that happen now.

**Comment by johnennewdeeson** [comment]
i don't think base url belongs in settings

**Comment by ghost** [comment]
i don't think base url belongs in the alias file so a settings include makes more sense

**Comment by angry-dan** [comment]
Agreed, although not sure we should be setting base URL anyway?

**Comment by ghost** [comment]
Settings files are now created at:

/var/www/settings/[shortname]/settings.inc
