### ISSUE TITLE
Create a drush7 command

### ISSUE THREAD

**Issue by johnennewdeeson** [dan-sprog/vdd#5]
I've edited the drush.rb file to checkout drush 6.2.0 and make that the default drush command

Also needs a drush7 command on its own codebase for running bleeding edge latest version for Drupal 8.

**Comment by angry-dan** [comment]
I was thinking about this... I'd like the drush version specified in the config file so that you can match it to the installed version on the host. They shouldn't be different ideally, but in some cases you might not bother with Drush on the host at all.

**Comment by angry-dan** [comment]
P.S agree that multi-drush would be useful.

**Comment by angry-dan** [comment]
I've made this configurable from the example configuration file.

**Comment by ghost** [comment]
You can add the following section to the drush part of the config file now to include a drush7 command

```
"version7": "7.0.0-alpha9"
```
