### ISSUE TITLE
Work out how to use SSL

### ISSUE THREAD

**Issue by johnennewdeeson** [dan-sprog/vdd#8]
Work out how to use SSL so we can have HTTPS connections without errors

**Comment by ghost** [comment]
I want to do this with Varnish, creating a wildcard *.dev certificate

**Comment by ghost** [comment]
apparently varnish doesn't listen to ssl requests:
https://www.varnish-cache.org/docs/trunk/phk/ssl.html

So should we use pound with varnish (like acquia recommends):
https://www.acquia.com/blog/why-pound-awesome-front-varnish

Or nginx (like acquia actually does):
https://www.digitalocean.com/community/tutorials/how-to-configure-varnish-cache-4-0-with-ssl-termination-on-ubuntu-14-04

**Comment by ghost** [comment]
i'm thinking nginx since its closest to reality

**Comment by angry-dan** [comment]
Nginx would seem like the better choice here.

**Comment by ghost** [comment]
nginx added as ssl terminator. Also added a cookbook to generate a *.dev wildcard certificate. nginx passes requests onto varnish which then passes onto apache.

Drupal needs to be told it is behind varnish cache and reverse proxy and https and cookie domains need properly setting to. All should be in its settings.php
