### ISSUE TITLE
make varnish start automatically

### ISSUE THREAD

**Issue by johnennewdeeson** [dan-sprog/vdd#9]
varnish needs to be started after vagrant up at the moment using

```
vagrant ssh
sudo /etc/init.d/varnish start
```

**Comment by angry-dan** [comment]
Probably just needs adding to the appropriate run level? Although packages
installed with APT should get all that stuff automatically. Is our chef
script any good?

**Comment by ghost** [comment]
there were two cookbooks, the first one I tried just crashed out in vagrant provision with some weird error that made no sense. the other is much better

**Comment by ghost** [comment]
Varnish and nginx now do start automatically
